Update 0-iamsomeoneelse

diff --git a/0x12-web_stack_debugging_2/0-iamsomeoneelse b/0x12-web_stack_debugging_2/0-iamsomeoneelse
--- a/0x12-web_stack_debugging_2/0-iamsomeoneelse
+++ b/0x12-web_stack_debugging_2/0-iamsomeoneelse
@@ -1,3 +1,15 @@
 #!/usr/bin/env bash
-# Runs whoami command under the user passed as an argument
-su "$1" -s /bin/bash -c 'whoami'
+# Check if an argument is provided
+if [[ $# -eq 0 ]]; then
+  echo "Please provide a user as an argument."
+  exit 1
+fi
+
+# Check if the user exists
+if ! id -u "$1" >/dev/null 2>&1; then
+  echo "User $1 not found."
+  exit 1
+fi
+
+# Run the whoami command as the specified user
+sudo -u "$1" whoami
